// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "BestSub API Support",
            "email": "support@bestsub.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "用户登录接口，验证用户名和密码，返回JWT令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户登出接口，使当前会话失效",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "使用刷新令牌获取新的访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新访问令牌",
                "parameters": [
                    {
                        "description": "刷新令牌请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.RefreshTokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "刷新令牌无效",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的所有活跃会话信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取用户会话列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SessionListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/sessions/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定ID的会话，使其失效",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "删除会话",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.UserInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/user/name": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改当前用户的用户名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "修改用户名",
                "parameters": [
                    {
                        "description": "修改用户名请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.UpdateUserInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户名修改成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "用户名已存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/user/password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改当前用户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "密码修改成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权或旧密码错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/config/items": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取系统所有配置项，支持按分组过滤和关键字搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "获取所有配置项",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置分组过滤",
                        "name": "group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键字搜索配置名或描述",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ConfigItemsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据请求数据中的ID批量更新配置项的值和描述",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "批量更新配置项",
                "parameters": [
                    {
                        "description": "更新配置项请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.UpdateConfigItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ConfigItemsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/config/items/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID获取指定的配置项详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "获取单个配置项",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配置项ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ConfigItemResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "配置项不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/system/health": {
            "get": {
                "description": "检查服务健康状态，包括数据库连接状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务正常",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.HealthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "服务不可用",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/system/live": {
            "get": {
                "description": "检查服务是否存活（简单的ping检查）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "存活检查",
                "responses": {
                    "200": {
                        "description": "服务存活",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/system/ready": {
            "get": {
                "description": "检查服务是否准备好接收请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "就绪检查",
                "responses": {
                    "200": {
                        "description": "服务就绪",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.HealthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "服务未就绪",
                        "schema": {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_bestruirui_bestsub_internal_api_models.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "新密码",
                    "type": "string",
                    "example": "new_password"
                },
                "old_password": {
                    "description": "旧密码",
                    "type": "string",
                    "example": "old_password"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.ConfigItemData": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "配置描述",
                    "type": "string",
                    "example": "是否启用代理"
                },
                "id": {
                    "description": "配置ID",
                    "type": "integer",
                    "example": 1
                },
                "value": {
                    "description": "配置值",
                    "type": "string",
                    "example": "true"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.ConfigItemResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "description": {
                    "description": "配置描述",
                    "type": "string",
                    "example": "是否启用代理"
                },
                "group_name": {
                    "description": "配置分组",
                    "type": "string",
                    "example": "proxy"
                },
                "id": {
                    "description": "配置ID",
                    "type": "integer",
                    "example": 1
                },
                "key": {
                    "description": "配置键",
                    "type": "string",
                    "example": "proxy.enable"
                },
                "type": {
                    "description": "配置类型",
                    "type": "string",
                    "example": "bool"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "value": {
                    "description": "配置值",
                    "type": "string",
                    "example": "true"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.ConfigItemsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "配置项列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ConfigItemResponse"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "description": "错误详情",
                    "type": "string",
                    "example": "Invalid request format"
                },
                "message": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "Bad Request"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.HealthResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "description": "数据库状态",
                    "type": "string",
                    "example": "connected"
                },
                "status": {
                    "description": "服务状态",
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "description": "检查时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00"
                },
                "version": {
                    "description": "版本信息",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "JWT访问令牌",
                    "type": "string",
                    "example": "access_token_string"
                },
                "expires_at": {
                    "description": "令牌过期时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string",
                    "example": "refresh_token_string"
                },
                "user": {
                    "description": "用户信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.UserInfo"
                        }
                    ]
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string",
                    "example": "refresh_token_string"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "新的JWT访问令牌",
                    "type": "string",
                    "example": "new_access_token_string"
                },
                "expires_at": {
                    "description": "新令牌过期时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "refresh_token": {
                    "description": "新的刷新令牌",
                    "type": "string",
                    "example": "new_refresh_token_string"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.SessionInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "expires_at": {
                    "description": "过期时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "description": "会话ID",
                    "type": "integer",
                    "example": 1
                },
                "ip_address": {
                    "description": "IP地址",
                    "type": "string",
                    "example": "192.168.1.1"
                },
                "is_active": {
                    "description": "是否活跃",
                    "type": "boolean",
                    "example": true
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "user_agent": {
                    "description": "用户代理",
                    "type": "string",
                    "example": "Mozilla/5.0..."
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.SessionListResponse": {
            "type": "object",
            "properties": {
                "sessions": {
                    "description": "会话列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.SessionInfo"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据"
                },
                "message": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.UpdateConfigItemRequest": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "description": "配置数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_bestruirui_bestsub_internal_api_models.ConfigItemData"
                    }
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.UpdateUserInfoRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "description": "新用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "github_com_bestruirui_bestsub_internal_api_models.UserInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "用户认证相关接口",
            "name": "认证"
        },
        {
            "description": "系统状态和健康检查接口",
            "name": "系统"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BestSub API",
	Description:      "BestSub - Best Subscription Manager API Documentation\n\nThis is the API documentation for BestSub, a subscription management system.\n\n## Authentication\nMost endpoints require authentication using JWT tokens.\nTo authenticate, include the JWT token in the Authorization header:\n`Authorization: Bearer <your-jwt-token>`\n\n## Error Responses\nAll error responses follow a consistent format with code, message, and error fields.\n\n## Success Responses\nAll success responses follow a consistent format with code, message, and data fields.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
